Repository Broaden-io/Broaden-io-client, pull requests merged in 2018-04, with the labels that each got.

#66 Refactored constants and reducers, added logger middleware, added err…
  package-lock.json
  package.json
  public/index.html
  src/actions/assessment.js
  src/actions/assessments.js
  src/actions/auth.js
  src/actions/rubric.js
  src/actions/rubrics.js
  src/reducers/assessment.js
  src/reducers/assessments.js
  src/reducers/auth.js
  src/reducers/rubric.js
  src/reducers/rubrics.js
  src/reducers/sidebarMini.js
  src/store/ConfigureStore.js
Labels: cleanup

#65 Refactoring the codes inside the SourceCodes for React Components
  src/components/ChartCard2.jsx
  src/components/DashboardOld.js
  src/components/Login.js
  src/components/ScoreCard.js
  src/components/SignUp.js
  src/components/loadingAnimation.js
  src/loadingStyles.js
Labels: cleanup, enhancement

#70 React test render
  .babelrc
  __TESTS__/ChartCard.spec.js
  __TESTS__/RadioButton.spec.js
  __TESTS__/react-testing.js
  jestSetUp.js
  package-lock.json
  package.json
  src/components/ChartCard.jsx
  src/components/Dashboard.js
  src/components/RadioButton.js
Labels: enhancement

#78 Made prev/next buttons fit for mobile and overall look better
  src/components/Rubric.js
Labels: enhancement

#85 Add delete functionality to learning actions
  package-lock.json
  package.json
  public/assets/css/material-dashboard.css
  public/assets/js/--jquery.select-bootstrap.js
  public/examples/learning-mockup.html
  public/examples/widgets.html
  public/index.html
  src/actions/learningAction.js
  src/components/Action.js
  src/components/ActionConfirmDeleteModal.js
  src/components/ActionCreateModal.js
  src/components/Assessment.js
  src/components/AssessmentOld.js
  src/components/Criterion.js
  src/components/CriterionOld.js
  src/components/Dashboard.js
  src/components/Learning.js
  src/components/Modal.js
  src/components/ModalWizard.js
  src/components/Rubric.js
  src/components/Sidebar.js
  src/reducers/learningAction.js
  src/store/ConfigureStore.js
Labels: enhancement
