Repository Broaden-io/Broaden-io-client, pull requests merged in 2018-03, with the labels that each got.

#28 Checking a checkbox repackages the rubric's snapshot and sends to the Assessment UPDATE route, then redraws the component with updated value
  package-lock.json
  src/actions/assessment.js
  src/components/Checkbox.js
  src/components/Criteria.js
  src/components/Rubric.js
  src/components/RubricsIndex.js
  src/reducers/assessment.js
Labels: help wanted

#31 Connect score card component to Dashboard
  src/actions/assessments.js
  src/components/Dashboard.js
  src/components/ScoreCard.js
  src/reducers/assessments.js
  src/store/ConfigureStore.js
Labels: enhancement

#46 Sign up refactor
  src/actions/auth.js
  src/components/SignUp.js
Labels: help wanted

#49 Update Rubric.js added back the .sort function to arrange the rubrics assessment, remove the Rubrics Component flashing and refactoring the code
  src/components/Rubric.js
Labels: good first issue, help wanted

#57 Added loading react animation to login.js, signup.js, and rubric.j
  package-lock.json
  package.json
  src/assets/css/material-dashboard-react.css
  src/components/Login.js
  src/components/SignUp.js
  src/components/loadingAnimation.js
  src/loadingStyles.js
Labels: enhancement
